language: python
python:
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"
install:
  - "pip install coverage"
# command to run tests
script: nosetests -v --with-coverage --cover-tests --cover-min-percentage=100